on: 
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - name: Release Version
        run: |
          echo "$(jq -r .version composer.json)-$(echo $GITHUB_SHA" | cut -c1-8)"
      - name: Get Pokemon name
        uses: ./ # Uses an action in the root directory
        with:
          who-to-greet: 'Mona the Octocat'
