on: 
  push:
    branches:
      - master
      - dev
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - dev
jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - uses: actions/checkout@v2
      - name: Set Version
        run: |
          echo "MDC_VERSION=$(jq -r .version composer.json)-$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set Tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "MDC_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Check ENV
        run: |
          echo "$BRANCH"
      - name: Print Version
        run: |
          echo "$MDC_VERSION"
