on: 
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - dev
jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - uses: actions/checkout@v2
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v4.5
      - name: Set Push Environment
        if: steps.branch-name.outputs.is_tag == 'false' && steps.branch-name.outputs.is_default == 'true'
        run: |
          echo "MDC_VERSION=$(jq -r .version composer.json)-$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV
          echo "BRANCH=${{ steps.branch-name.outputs.ref_branch }}" >> $GITHUB_ENV
      - name: Set PR Environment
        if: steps.branch-name.outputs.is_tag == 'false' && steps.branch-name.outputs.is_default == 'false'
        run: |
          echo "MDC_VERSION=$(jq -r .version composer.json)-$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV
          echo "BRANCH=${{ steps.branch-name.outputs.base_ref_branch }}" >> $GITHUB_ENV
      - name: Set Tags Environment
        if: steps.branch-name.outputs.is_tag == 'true'
        run: |
          echo "MDC_VERSION=$(jq -r .version composer.json)-$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV
          echo "BRANCH=${{ steps.branch-name.outputs.tag }}" >> $GITHUB_ENV
      - name: Check ENV
        run: |
          echo "$BRANCH"
          echo "$MDC_VERSION"
          env
